#install.packages('lasso2')
library(leaps)
library(lasso2)
rm(list=ls())
data(Prostate)
cor(Prostate)
test = lm(lpsa ~ ., data = Prostate)
summary(test)
nvmax  = c(1:7)
regfit_full = regsubsets(lpsa ~ ., data = Prostate, nvmax = nvmax)
coef(regfit_full,2)
